services:
  rocker:
    build:
      context: .  # Assumes the Dockerfile is in the current directory
      dockerfile: Dockerfile.rocker
    ports:
      - "8788:8788"
    expose:
      - 8788
    volumes:
      - ./runtime:/home/rstudio/workspace
    env_file: .rstudio.env